### ISSUE TITLE
Notes field ignores line breaks in display mode

### ISSUE THREAD

**Issue by chaosbunker** [padloc/padloc#255] opened 2019-12-29 13:43 UTC
Drafting a multiple line note works as expected
<img width="476" alt="Screenshot 2019-12-29 at 14 23 36" src="https://user-images.githubusercontent.com/16366980/71557458-70fa1d00-2a3e-11ea-8549-f4814bf48be8.png">
but as soon as it is saved, this is what it looks like
<img width="487" alt="Screenshot 2019-12-29 at 14 24 19" src="https://user-images.githubusercontent.com/16366980/71557464-8a02ce00-2a3e-11ea-9180-644d953b73e0.png">

1. What I'm expecting to see is that the line breaks are shown when viewing the field.

2. When editing that note it is possible for me to highlight a single word, but copying that single word does not work. It always copies the entire note. An example of when this would be useful for me is in a note that contains a list of 2FA recovery codes and I need to copy a single code.

	> This
is
a
test

3. When the note is very long, the entire note is displayed in a card, which can be a bit annoying if one wants to get to a card that's below the note. What would like to see is that the card containing the note has a max-height and clicking on the note expands it. When expanded, it would be useful to be able to highlight text.

4. When editing that large note it would also be better to have a scrollable field with a max-height instead of a fully expanded field.

**Comment by MaKleSoft** [comment] 2019-12-29 14:56
> What I'm expecting to see is that the line breaks are shown when viewing the field.

yep, this looks like a regression. Expect this to be fixed with the next update.

> When editing that note it is possible for me to highlight a single word, but copying that single word does not work. It always copies the entire note. An example of when this would be useful for me is in a note that contains a list of 2FA recovery codes and I need to copy a single code

Make sense! (I think I've heard this one before, actually. Would you mind creating a new issue for this? (I assume this applies to all field types, not just notes)

**Closed** 2020-01-09 16:51 UTC
Labels: bug
