### ISSUE TITLE
Camera not working in vault section

### ISSUE THREAD

**Issue by AnkitCWappgo** [padloc/padloc#658] opened 2022-12-28 08:50 UTC
![Screenshot_2022-12-28-14-17-56-561_com brave browser](https://user-images.githubusercontent.com/82019650/209785274-381a370d-ffd3-4a81-8543-3b09f7451765.jpg)

**Comment by BrunoBernardino** [comment] 2022-12-29 09:12
Hi @AnkitCWappgo can we get a bit more details (Padloc app version, iOS/Android, which version, and if you've enabled camera access)? I can't reproduce this on Android 13, running Padloc 4.2.0.

**Comment by MaKleSoft** [comment] 2022-12-29 10:40
@AnkitCWappgo A bit off-topic, but I've noticed that you're using a custom skin (different color scheme and font). Cool to see this in the wild, since it's not even documented yet! Would you mind telling us how you are using Padloc and what you are building your custom version for?

**Comment by MaKleSoft** [comment] 2023-01-09 09:55
Closing this due to missing feedback. @AnkitCWappgo Let me know if this is still an issue and we can reopen.

**Closed by MaKleSoft** 2023-01-09 09:55 UTC
Labels: bug
