### ISSUE TITLE
Desktop app saves item with all fields empty

### ISSUE THREAD

**Issue by Raph33** [padloc/padloc#264] opened 2020-01-09 13:34 UTC
When creating a new item, filling all fields, and saving, the desktop (Mac OS) saves the item with all fields empty. 

This doesn't happen all the time. It happens often (probably 40% of the time) and I haven't been able to identify any pattern on why/when this happens.

<img width="494" alt="Screen Shot 2020-01-09 at 8 30 33 AM" src="https://user-images.githubusercontent.com/27868414/72071786-98f94400-32ba-11ea-9c7d-cb93a1e941c6.png">

**Comment by MaKleSoft** [comment] 2020-01-09 15:51
Yeah, I've observed this as well. Looks like a race condition. We'll try to have this fixed with the next release.

**Comment by Raph33** [comment] 2020-01-25 18:18
I wonder if this is linked: I've been experiencing major issues when editing an item (either editing fields or deleting the item all together). I make the changes and it seems to be taken into account, but when I click "Save" and the item closes, the changes are not applied. When deleting an item, after clicking "Save", the item actually disappears from the list of items but reappears a few seconds later. Should I create a separate issue?

**Comment by MaKleSoft** [comment] 2020-01-26 09:11
Hm, it does seem like these are related, possibly even linked to https://github.com/padloc/padloc/issues/233. From what you're describing it sounds like a timing issue that causes the background sync to interfere with editing. I'll investigate.

**Comment by Raph33** [comment] 2020-02-08 14:43
@MaKleSoft do you have any update on this? 

To be honest, it makes Padloc almost unusable for me. I've had several instances where I changed a password but the new password wasn't saved, so I was locked out of my accounts and had to reset the passwords (including for a banking portal, where resetting a password isn't trivial...).

**Comment by MaKleSoft** [comment] 2020-02-09 10:28
@Raph33 Unfortunately, I haven't had any luck reproducing this yet, and we haven't received any reports similar to yours that would help us zero in on the problem. It definitely sounds like a synchronization issue, like your changed data being overwritten by the data fetched from the server but it's hard to say without being able to reproduce it. Have you identified any pattern in when this happens, like does it happen only for a specific vault, or any specific device?

**Comment by Raph33** [comment] 2020-02-12 17:02
I couldn’t identify a pattern. It happens both when creating new items and when editing existing ones. Ill try and see if I can identify a pattern. And it's happened exclusive on Mac OS

**Comment by Raph33** [comment] 2020-02-24 02:39
I can now confirm that it's also happening on the Android app. Which would confirm your suspicion that it has to do with a synchronization issue.
And I still couldn't identify a pattern, but just confirming that it does happen both when creating new items and when editing existing items.

**Comment by MaKleSoft** [comment] 2020-02-29 08:59
And this happens for all your vaults or only a specific one?

**Comment by Raph33** [comment] 2020-02-29 21:20
Hard to tell, I only use my personal Vault

**Comment by Raph33** [comment] 2020-03-19 17:58
This issue seems to not be happening anymore. @MaKleSoft did you change something in the back-end?

**Comment by MaKleSoft** [comment] 2020-03-21 06:53
Not really... Let's keep an eye on it.

**Comment by MaKleSoft** [comment] 2020-04-19 06:41
So, just a quick update on this: We're still not 100% what's causing this but we've identified a race condition that could potentially cause this behavior. Basically if you're submitting a change while the app is in the process of pushing a vault update (most likely waiting for a response from the server), this change is then discarded. The timing has to be just right which is probably why this has been so hard to reproduce. The quality of your internet connection also plays a role so if this has been happening more often while on a slow network this is probably why. You can expect a fix for this in the next release. In the meantime, one workaround is to simply wait a little before clicking the save button on a new item (count to 10 Mississippi maybe).

**Comment by Raph33** [comment] 2020-04-20 18:59
That would make sense; I stopped experiencing the issue immediately after upgrading my internet connection. 

Not sure if it's linked, but one issue that I'm still experiencing is that when creating a new item, after entering the name, type, and location of the item, the item is created (empty) and closed; I am not taken to the screen to fill/edit fields. So I need to find the item and edit it.

**Comment by MaKleSoft** [comment] 2020-06-30 06:34
This should be resolved as of v3.1.0.

**Closed by MaKleSoft** 2020-06-30 06:34 UTC
