### ISSUE TITLE
[Issue][Android] Padloc does not automatically save after editing a Vault Item

### ISSUE THREAD

**Issue by Terkyz** [padloc/padloc#565] opened 2022-08-22 19:21 UTC
When I edit a Vault Item and immediately edit another, without giving Padloc enough time to perform its automatic save, Padloc doesn't save the changes from the first edit, only from the second edit and the data from the first edit just doesn't change!

Android 11 / Samsung Galaxy a10 / v.4.0.2 / Google Playstore

**Comment by BrunoBernardino** [comment] 2022-09-08 10:14
Hi @Terkyz can you share a bit more information about this? Are you on a slow connection when this happens, or is there a way to consistently get this problem (is this an item you've created elsewhere and hasn't synchronized, or something)?

I'm asking because I'm having trouble reproducing this problem by simply trying to update an item two times in a row, quickly (on the same or different fields).

**Comment by MaKleSoft** [comment] 2022-09-08 10:55
FWIW, I also haven't been able to reproduce this on my Android phone.

**Comment by Terkyz** [comment] 2022-09-08 15:55
> Hi @Terkyz can you share a bit more information about this? Are you on a slow connection when this happens, or is there a way to consistently get this problem (is this an item you've created elsewhere and hasn't synchronized, or something)?
> 
> I'm asking because I'm having trouble reproducing this problem by simply trying to update an item two times in a row, quickly (on the same or different fields).

Hmm, I hadn't thought about it although it's true, although it wasn't a slow connection at all I was using mobile data

Currently I can't replicate it (because i'm not at home), but basically I migrated from Keepass to Padloc and I had to edit all my items (more than 40), and I quickly edited inside Padloc (in less than a minute) the name, the icon, I deleted some data and passed to another vault item without waiting for Padloc to save automatically

**Comment by BrunoBernardino** [comment] 2022-09-09 05:18
Ok, please let us know if you can replicate it and a few more details on how!

**Comment by BrunoBernardino** [comment] 2022-09-24 13:23
Closing for now, feel free to reopen if you can replicate it.

**Closed by BrunoBernardino** 2022-09-24 13:23 UTC
Labels: bug, blocked
