### ISSUE TITLE
Biometric authentication setup fails on Tauri macOS app

### ISSUE THREAD

**Issue by bengiv** [padloc/padloc#692] opened 2023-03-05 11:39 UTC
```
Setup Failed
Biometric authentication failed! Canceling Setup. (Reason: The RP ID "web.padloc.app" is invalid for this domain)
```

**Comment by MaKleSoft** [comment] 2023-03-08 13:12
Duplicate of https://github.com/padloc/padloc/issues/600

**Closed by MaKleSoft** 2023-03-08 13:12 UTC
